AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Blog - BlogPost Table
Parameters:
  Environment:
    Description: Environment
    Type: String
Resources:
  BlogPostAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: BlogPost Api Gateway
      Description: BlogPost Api Gateway
      MethodSettings:
        - ResourcePath: /blogposts
          HttpMethod: POST
        - ResourcePath: /blogposts
          HttpMethod: GET
      CacheClusterEnabled: False
      DisableExecuteApiEndpoint: False
      EndpointConfiguration:
        Type: REGIONAL
      Mode: overwrite
      StageName: !Ref Environment
      TracingEnabled: False
