AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Blog - BlogPost Table
Parameters:
  Environment:
    Description: Environment
    Type: String
Resources:
  BlogPostAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: BlogPost Api Gateway
      Description: BlogPost Api Gateway
      Body:
        openapi: 3.0.0
        info:
          title: BlogPost API
          description: BlogPost API Gateway
          version: 0.0.1
        paths:
          /blogposts:
            options:
            summary: OPTIONS for blogpost
            description: OPTIONS for blogpost
            responses:
              "200":
                description: CORS content for blogpost
      CacheClusterEnabled: False
      DisableExecuteApiEndpoint: False
      EndpointConfiguration:
        Type: REGIONAL
      Mode: overwrite
      StageName: !Ref Environment
      TracingEnabled: False
