AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Blog - BlogPost Table
Parameters:
  Environment:
    Description: Environment
    Type: String

Resources:
  BlogPostAPIGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "Api gateway BlogPost - ${Environment}"
      Description: !Sub "Api gateway for BlogPost - ${Environment}"
      DisableExecuteApiEndpoint: False
      EndpointConfiguration:
        Types:
          - REGIONAL
      FailOnWarnings: False
      Mode: overwrite
      Body: null
