AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Blog - BlogPost Table
Parameters:
  Environment:
    Description: Environment
    Type: String
  BlogPostLambdaPutArn:
    Description: BlogPost Lambda Arn
    Type: String
Resources:
  BlogPostAPIGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "Api gateway BlogPost - ${Environment}"
      Description: !Sub "Api gateway for BlogPost - ${Environment}"
      DisableExecuteApiEndpoint: False
      EndpointConfiguration:
        Types:
          - REGIONAL
      FailOnWarnings: False
      Mode: overwrite
      BodyS3Location:
        Bucket:
          Fn::Join:
            [
              "-",
              [
                !Ref Environment,
                escoladesoftware-blog-blogpost-api-definition-bucket,
              ],
            ]
        Key: openApiBlogPost.yaml

  BlogPostPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BlogPostAPIGateway
      ResourceId: !GetAtt
        - BlogPostAPIGateway
        - RootResourceId
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BlogPostLambdaPutArn}/invocations"
