AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Blog - BlogPost Table
Parameters:
  Environment:
    Description: Environment
    Type: String
Resources:
  BlogPostAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      CacheClusterEnabled: False
      Description: BlogPost Api Gateway
      DisableExecuteApiEndpoint: False
      EndpointConfiguration:
        Type: REGIONAL
      Mode: overwrite
      Name: BlogPost Api Gateway
      OpenApiVersion: 3.0.0
      StageName: !Ref Environment
      TracingEnabled: False
