AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Blog - BlogPost API
Parameters:
  Environment:
    Description: Environment
    Type: String
Resources:
  BlogPostAPIGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "Api gateway BlogPost - ${Environment}"
      Description: !Sub "Api gateway for BlogPost - ${Environment}"
      DisableExecuteApiEndpoint: False
      EndpointConfiguration:
        Types:
          - REGIONAL
      FailOnWarnings: False
      Mode: overwrite

  BlogPostAPIGatewayBlogPostResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      RestApiId: !Ref BlogPostAPIGateway
      ParentId: !GetAtt
        - BlogPostAPIGateway
        - RootResourceId
      PathPart: "blogposts"

  BlogPostAPIGatewayBlogPostPost:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      ApiKeyRequired: False
      HttpMethod: POST
      Integration:
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - StatusCode: 201
          - StatusCode: 400
          - StatusCode: 500
        TimeoutInMillis: 2000
        Type: AWS_PROXY
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${Environment}_PutBlogPostFn/invocations"
      MethodResponses:
        - StatusCode: 201
        - StatusCode: 400
        - StatusCode: 500
      OperationName: POST /blogposts
      ResourceId: !Ref BlogPostAPIGatewayBlogPostResource
      RestApiId: !Ref BlogPostAPIGateway
