AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Blog - BlogPost Table
Parameters:
  Environment:
    Description: Environment
    Type: String
Resources:
  BlogPostAPIGatewayARN:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: API Gateway ID
      Name:
        Fn::Join: ["/", [!Sub "/${Environment}", BlogPost, APIGateway, Id]]
      Tags:
        Environment: !Ref Environment
      Type: String
      Value: !Ref BlogPostAPIGateway

  BlogPostAPIGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "Api gateway BlogPost - ${Environment}"
      Description: !Sub "Api gateway for BlogPost - ${Environment}"
      DisableExecuteApiEndpoint: False
      EndpointConfiguration:
        Types:
          - REGIONAL
      FailOnWarnings: False
      Mode: overwrite
      Body:
        openapi: 3.0.0
        info:
          title: BlogPost API
          description: BlogPost API Gateway
          version: 0.0.1
        paths:
          /blogposts:
            post:
              summary: insert a blogpost
              description: insert a blogpost
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        id:
                          description: id of blogpost
                          type: string
                        title:
                          description: title of blogpost
                          type: string
                        category:
                          description: category of blogpost
                          type: string
                        content_bucket_key:
                          description: content bucket key
                          type: string
                        image_principal_key:
                          description: image principal key
                          type: string
                        post_date:
                          description: post date of blogpost
                          type: string
                        resume:
                          description: resume of blogpost
                          type: string
                      required:
                        - title
                        - category
                        - resume
                        - post_date
                        - image_principal_key
              responses:
                "201":
                  description: blogpost insert with success
                "400":
                  description: error with input object
                "500":
                  description: internal server error
Outputs:
  BlogPostAPIGateway:
    Description: BlogPost Api Gateway
    Value: !Ref BlogPostAPIGateway
    Export:
      Name:
        Fn::Join: ["-", [!Ref Environment, BlogPostAPIGateway]]
